# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DTMvvm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'Action', '~> 4.2.0'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ObjectMapper'
  pod 'PureLayout', '~> 3.1.6'
  pod 'Moya'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
  
end
